= Building biber under Alpine Linux

The TeX Live distribution does not provide biber for MUSL based Linux distros
such as Alpine.

This project provides the means to build biber under Alpine Linux from the
source. Run

----
docker build -t krumeich/biber-alpine .
----

to build the image. This takes some time, as all the perl dependencies are
downloaded and installed. Then run

----
docker run -v $PWD:/usr/local/bin krumeich/biber-alpine
----

to build the biber binary. Mounting the `$PWD` as `/usr/local/bin` to make the
directory visible in which the build process installs the binary.

== Notes

* Passing `-e branch=<branchname>` causes the branch `<branchname>` to be
  built. If the parameter is omitted, `branch` will default to `master`:
+
----
docker run -v $PWD:/usr/local/bin -e branch=krumeich/musl krumeich/biber-alpine
---- 

* Passing `-e repo=<reponame>` causes the repository `<reponame>` to be
  built. If the parameter is omitted, `repo` will default to `plk/biber`:
+
----
docker run -v $PWD:/usr/local/bin -e repo=krumeich/biber krumeich/biber-alpine
----

Of course you can combine both variants to build an arbitrary branch from an
arbitrary biber fork.

* Alternatively, if you have `make` installed, use `make image` to create the
  image, then use `make biber` to build biber. To pass a particular branch name,
  set the environment variables `BRANCH` and/or `REPO` on the same command line:
+   
----
BRANCH=krumeich/musl REPO=krumeich/biber make biber
----
